### ISSUE TITLE
- Esse teste também não considera que o fixedQuorum está 1, logo o teste está passando por acaso. Avaliar outros testes e ajustar.

### ISSUE THREAD

**Issue by gladsjr** [RBBNet/Permissionamento#22]
```
  //TODO - Esse teste também não considera que o fixedQuorum está 1, logo o teste está passando por acaso. Avaliar outros testes e ajustar. 
```

https://github.com/RBBNet/Permissionamento/blob/c151297e4a8323ce5e7b7153894a56e5fe38b716/test/test-account-admin.js#L35

**Comment by Lionel-Rocha** [comment]
Consertado - mudei para "majority" no beforeEach

**Comment by gladsjr** [comment]
Resolvemos realizar uma análise de segurança mais profissional para definir os requisitos a serem implementados, logo, temporariamente, essa issue, assim como outras perderam o sentido.
