### ISSUE TITLE
Retorno false do add() não deveria atualizar lasCallTimestamp

### ISSUE THREAD

**Issue by gladsjr** [RBBNet/Permissionamento#7]
https://github.com/RBBNet/Permissionamento/blob/b6987ec91f379c9a0a3c127e376410269590620c/contracts/Admin.sol#L53

**Comment by Lionel-Rocha** [comment]
Senhor, esse é o "else". No retorno do false não tem atualização mesmo.

**Comment by Lionel-Rocha** [comment]
Issue consertada

**Comment by Lionel-Rocha** [comment]
Fechei a issue!

**Comment by gladsjr** [comment]
Não há mais necessidade.
