### ISSUE TITLE
Melhorar cobertura de caminhos de execução nos testes de removeAdmin

### ISSUE THREAD

**Issue by gladsjr** [RBBNet/Permissionamento#9]
https://github.com/RBBNet/Permissionamento/blob/b6987ec91f379c9a0a3c127e376410269590620c/test/test-admin.js#L116

**Comment by gladsjr** [comment]
É a mesma situação do addAdmin, na verdade. Apenas coloquei em outro issue.

**Comment by Lionel-Rocha** [comment]
Foi!

**Comment by gladsjr** [comment]
Não há mais necessidade.
